### ISSUE TITLE
Missing a "TYPE_IS"

### ISSUE THREAD

**Issue by jdiaz360** [KilikFr/TableBundle#15]
Hi! I'm trying to use a FilterSelect with a nullable field (googleAuthenticatorSecret) but y don't have a TYPE_IS to get something like this: ```WHERE field is null``` | ```WHERE field is not null```

```php
$table->addColumn(
    (new Column())
        ->setRaw(true)
        ->setLabel('MFA')
        ->setSort(['u.googleAuthenticatorSecret' => 'asc'])
        ->setFilter(
            (new FilterSelect())
                ->setField('u.googleAuthenticatorSecret')
                ->setName('u_googleAuthenticatorSecret')
                ->setPlaceholder('-- ALL --')
                ->setChoices([
                    'Si' => 'null',
                    'No' => 'not null'
		])
        )
);
```

**Comment by mitch10593** [comment]
Hi !
You're right.
It's probably a feature to plan.

Waiting for it, you should look here:
https://github.com/KilikFr/TableDemo/blob/master/src/Kilik/TableDemoBundle/Controller/ProductController.php#L98

I think it's the way to handle the filter has you want...

**Comment by jdiaz360** [comment]
@mitch10593 Thank you! your comment was very helpful! 
this is a great bundle, I hope for a new release!

Regards!
