### ISSUE TITLE
Filter by url query string

### ISSUE THREAD

**Issue by jedi4z** [KilikFr/TableBundle#17]
Hi! I need filtering the table by a url with query string, something like this: http://localhost/bank-account/list?state=pending

Is it possible? or how can I redirect to the table pre filtered?

Regards!

**Comment by mitch10593** [comment]
Hi,

There is more than one way to do filtering...

To apply hard coded filters without columns or addition frontend filters, you can:
- use a variable in your route (ex: /list-by-state/{state})
- get this variable and pass it to getTable method
- use, in getTable, this variable to customize the query builder
- and don't forget to pass it to the ajax callback

I have just added an example to see how to do that:

Running demonstration:
(filtering on an organisation)
http://tabledemo.kilik.fr/organisation/33/product/list

And here, the controller (think to watch linked views): 
https://github.com/KilikFr/TableDemo/blob/master/src/Kilik/TableDemoBundle/Controller/Organisation/ProductController.php

**Comment by mitch10593** [comment]
Without feedback on my last answer, I close this issue.
