### ISSUE TITLE
incompatible with symfony 4 

### ISSUE THREAD

**Issue by mitch10593** [KilikFr/TableBundle#22]
kilik/table-bundle is not compatible with symfony 4, because:
sensio/generator-bundle v3.0.7 requires symfony/framework-bundle ~2.7|~3.0

**Comment by benito103e** [comment]
From SensioGeneratorBundle documentation :
WARNING: This bundle does not support Symfony 4. It also does not support the new bundle-less directory structure as created by Symfony Flex. Use the Maker bundle instead.
