### ISSUE TITLE
Invalid default template in Symfony 4

### ISSUE THREAD

**Issue by mschop** [KilikFr/TableBundle#30]
Hi,

when I do not explicitely set the template for a form manually like this:

```
$form->setTemplate('@KilikTable/_defaultTable.html.twig');
```

I get the following error in the ajax call:
```
Unable to find template "KilikTableBundle::_defaultTable.html.twig" (looked into: /project/templates, /project/templates, /project/vendor/symfony/twig-bridge/Resources/views/Form).
```

This seems like an invalid default value to me.

Best Regards
mschop

**Comment by benito103e** [comment]
Hello,
You need to use the new reference notation for twig templates (see #24)
`->setTemplate('_table/_table.html.twig')`

So you're right, default template reference throw exception.
