### ISSUE TITLE
Uninitialized Column->autoReverse causes Warning and failure of resort

### ISSUE THREAD

**Issue by mschop** [KilikFr/TableBundle#32]
Hi,

when sorting by a column, a PHP warning is thrown, which causes the AJAX-Request to fail in dev environment. This is the warning:

    Warning: count(): Parameter must be an array or an object that implements Countable

And this is the Stack-Trace:

	ErrorException
	in vendor/kilik/table/Components/Column.php (line 238)
	in vendor/kilik/table/Services/TableService.php->getAutoSort (line 232)
	in vendor/kilik/table/Services/AbstractTableService.php->getRows (line 159)
	AbstractTableService->handleRequest(object(Table), object(Request)) in src/Controller/Backend/UserController.php (line 93)
	in vendor/symfony/http-kernel/HttpKernel.php->listAjax (line 149)
	in vendor/symfony/http-kernel/HttpKernel.php->handleRaw (line 66)
	in vendor/symfony/http-kernel/Kernel.php->handle (line 188)
	Kernel->handle(object(Request)) in public/index.php (line 37) 

Best Regards
mschop

**Comment by mitch10593** [comment]
Thanks for this report, and for your fix in #33
