### ISSUE TITLE
Installation under symfony 3.2

### ISSUE THREAD

**Issue by fastclicker** [KilikFr/TableBundle#5]
Hi Folks,

your database component is looking great. 

I try to install via   

`composer install kilik/table`

wich leads to an error:
 

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for kilik/table ^0.2.1 -> satisfiable by kilik/table[0.2.1].
>     - kilik/table 0.2.1 requires twig/twig >=1.8,<2.0-dev -> satisfiable by twig/twig[1.x-dev, v1.10.0, v1.10.1, v1.10.2, v1.10.3, v1.11.0, v1.11.1, v1.12.0, v1.12.0-RC1, v1.12.1, v1.12.2, v1.12.3, v1.13.0, v1.13.1, v1.13.2, v1.14.0, v1.14.1, v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.8.0, v1.8.1, v1.8.2, v1.8.3, v1.9.0, v1.9.1, v1.9.2] but these conflict with your requirements or minimum-stability.

wich seems to be correct. Since min. twig 2.0 is standard for symfony 3.2.
Am I wrong or can a change something to get it running with symfony 3.2  (twig 2.0 / twig 2.1)?

Regards
FastClicker

**Comment by mitch10593** [comment]
Hi,

I have tried to install kilik/table on a new fresh install...:

symfony new test-kilik-table
cd test-kilik-table
composer require kilik/table

Everything worked well.
The twig version on new Symfony project (3.2.8) is:
        "twig/twig": "^1.0||^2.0"

So, I have just updated kilik/table with same constraints.

You can use composer require kilik/table dev-master (a new tag is planned for today, with a fix on Filter::TYPE_IN).

**Comment by mitch10593** [comment]
KilikTable has been tested with Symfony 3.1, 3.2 and 3.3.

So, I'm closing this issue.
