### ISSUE TITLE
twig templates with trans and capitalize

### ISSUE THREAD

**Issue by erdnax123** [KilikFr/TableBundle#77]
```twig
{{ '...'|trans|capitalize }}
```
is a very bad combination. capitalize in Twig means the 1st letter upper and all others lower. For languages where nouns are capitalized, this creates unnecessary problems. So I have to overwrite all the templates that I use.

**Comment by mitch10593** [comment]
I agree:  You can remove this capitalize filter (and avoid to rewrite all templates)

**Comment by mitch10593** [comment]
done in #78 , thanks you @erdnax123

**Comment by mitch10593** [comment]
Hi @erdnax123 , this fix (and others) are now in 2.8.4 tag
